#!/bin/bash

rte_ip=$1
pikvm_ip=$2
image=$3
# shellcheck disable=SC2034
image_size=$4 # unused

if [ -z "$image" ]; then
    echo "No image to flash, successfully doing nothing."
    exit 0
fi

if [ ! -f "$image" ]; then
    echo "error: couldn't find '$image'" 1>&2
    exit 1
fi

web_dir=/srv/www/openqa
script_dir=$(dirname "$(readlink -f "$0")")
image_name=$(basename "$image")

ln -fs "$script_dir/ks.cfg" "$web_dir/ks.cfg"

echo "Assuming '$image_name' is already connected on PiKVM side"
