#!/bin/bash

rte_ip=$1
pikvm_ip=$2
image=$3
# shellcheck disable=SC2034
image_size=$4 # unused

if [ ! -f "$image" ]; then
    echo "error: couldn't find '$image'" 1>&2
    exit 1
fi

image_name=$(basename "$image")

echo "Assuming '$image_name' is already connected on PiKVM side"
