#!/bin/bash

set -e

web_dir=$1
iso_image=$2
# shellcheck disable=SC2034
iso_image_size=$3 # unused

if [ $# -lt 2 ]; then
    echo "error: Not enough arguments: $#." 1>&2
    for arg; do
        echo " - '$arg'." 1>&2
    done
    exit 1
fi

if [ -z "$iso_image" ]; then
    echo "error: No ISO image to flash." 1>&2
    exit 1
fi

if [ ! -f "$iso_image" ]; then
    echo "error: couldn't find '$iso_image'" 1>&2
    exit 1
fi

### Mount ISO and prepare other files accessed over the network ###
### =========================================================== ###

echo "flash: setting up data for network boot"

sudo umount --quiet "$web_dir/iso" || true
mkdir -p "$web_dir/iso"
sudo mount -t iso9660 -o ro,nodev,nosuid,noexec "$iso_image" "$web_dir/iso"
